apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: ollama
spec:
  type: LoadBalancer
  selector:
    name: openwebuipd
  ports:
  - port: 8080
    name: http
    targetPort: 8080
    protocol: TCP